language: python
sudo: false
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - 3.7-dev
  - pypy
  - pypy3.5
install:
  - pip install pep8
  - pip install -e .
script:
  # Guard against invalid escapes in strings, like '\s'.
  - python -We:invalid -m compileall -f mpmath -q
  - pep8
  - py.test
notifications:
  email: false
